language: cpp
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      dist: trusty
      env: BUILD_TYPE=Debug
    - os: linux
      dist: trusty
      env: BUILD_TYPE=MinSizeRel
    - os: linux
      dist: trusty
      env: BUILD_TYPE=RelWithDebInfo
    - os: osx
      osx_image: xcode9.2
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode9.2
      env: BUILD_TYPE=MinSizeRel
    - os: osx
      osx_image: xcode9.2
      env: BUILD_TYPE=RelWithDebInfo
    - os: osx
      osx_image: xcode9.2
      env: BUILD_TYPE=iOS
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libpulse-dev
      - libsdl2-dev
      - libvorbis-dev
      - ninja-build
      - pulseaudio
cache:
  directories:
    - local
before_install:
  - tools/travis.sh before_install
script:
  - tools/travis.sh script
after_success:
  - tools/travis.sh after_success
notifications:
  email: false
