language: cpp
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      dist: trusty
      env: BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libpulse-dev
            - libsdl2-dev
            - ninja-build
            - pulseaudio
    - os: linux
      dist: trusty
      env: BUILD_TYPE=MinSizeRel
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libpulse-dev
            - libsdl2-dev
            - ninja-build
            - pulseaudio
    - os: linux
      dist: trusty
      env: BUILD_TYPE=RelWithDebInfo
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libpulse-dev
            - libsdl2-dev
            - ninja-build
            - pulseaudio
    - os: osx
      osx_image: xcode9.4
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode9.4
      env: BUILD_TYPE=MinSizeRel
    - os: osx
      osx_image: xcode9.4
      env: BUILD_TYPE=RelWithDebInfo
    - os: osx
      osx_image: xcode9.4
      env: TARGET_OS=iOS
    - language: android
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-27
      jdk: openjdk8
      env: TARGET_OS=Android
cache:
  directories:
    - local
install:
  - tools/build-ci.sh install
script:
  - tools/build-ci.sh build
  - tools/build-ci.sh test
after_success:
  - tools/build-ci.sh after_success
notifications:
  email: false
