language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - ninja-build
install:
  - mkdir local
  - curl -LO http://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.sh
  - sh cmake-3.3.2-Linux-x86_64.sh --prefix=local --skip-license
  - export CC=gcc-4.9 CXX=g++-4.9 PATH=$(pwd)/local/bin:$PATH
script:
  - mkdir $TRAVIS_BUILD_DIR-build
  - cd $TRAVIS_BUILD_DIR-build
  - GENERATOR=Ninja $TRAVIS_BUILD_DIR/tools/build.sh -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DUNIT_TESTS=1 -DUSE_PHYSICS=1 -DUSE_SPINE=1
  - ./rainbow
after_success:
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$CMAKE_BUILD_TYPE" == "Debug" ]]; then cp -r $TRAVIS_BUILD_DIR-build/CMakeFiles/rainbow.dir/src .; fi
  - if [[ "$CMAKE_BUILD_TYPE" == "Debug" ]]; then bash <(curl -s https://codecov.io/bash) -x gcov-4.9; fi
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - tn0502@gmail.com
env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=MinSizeRel
  - CMAKE_BUILD_TYPE=RelWithDebInfo
os:
  - linux
sudo: false
