site_name: Rainbow
repo_url: https://bitbucket.org/tido/rainbow
copyright: Copyright &copy; 2010-15 Bifrost Entertainment AS and Tommy Nguyen.
pages:
  - [index.md, Home]
  - [getting_started/quick_start.md, Getting Started, Quick Start Guide]
  - [getting_started/cpp_basics.md, Getting Started, C++ Basics]
  - [getting_started/lua_basics.md, Getting Started, Lua Basics]
  - [programming/development/building_rainbow_for_pc.md, Development Setup, Building Rainbow for PC]
  - [programming/cpp/input.md, C++ Programming Guide, Input]
  - [programming/cpp/sprite_sheet_animations.md, C++ Programming Guide, Sprite Sheet Animations]
  - [programming/cpp/timers.md, C++ Programming Guide, Timers]
  - [programming/cpp/transitions.md, C++ Programming Guide, Transitions]
  - [programming/lua/api.md, Lua Programming Guide, Lua API]
  - [license.md, About, License]
theme: readthedocs
docs_dir: doc
markdown_extensions: [codehilite, smarty]
